spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgrespw
    url: jdbc:postgresql://localhost:49153/postgres
  jpa:
    hibernate:
      ddl-auto: create
jwt:
  secret: kameleon82